# Generated by Django 3.1.5 on 2021-01-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='from_signal',
            field=models.BooleanField(default=False),
        ),
    ]
